spring:
    application:
        name: orderService
    datasource:
        url: jdbc:postgresql://localhost:5432/resumeService
        username: postgres
        password: postgres
    cloud:
        loadbalancer:
            enabled: false
server:
    port: 8081
jwt:
    auth:
        converter:
            principal-attribute: preferred_username
            resource-id: order_client